selections:
  track:
    pt_min: 0.150

# remove the jet_finder section below if jets are not needed in analysis
jet_finder:
  R: 0.4
  alg: antikt
  pT_min: 10

analysis:
  pt_min_eec: 1.0

output:
  bins:
    track_pT: ['log', 0.1, 20, 300]
    jet_pT: ['lin', 0, 200, 200]
    jet_pT_coarse: ['custom', [5, 20, 40, 60, 80, 100, 150, 200]]
    RL: ['log', 1.0e-3, 1, 30]
  histograms:
    # define histograms with bins described in `bins`
    track_pT: [1, "track_pT", "Track #it{p}_{T} spectrum;#it{p}_{T} (GeV);dN/d#it{p}_{T}", track_pT]
    jet_pT: [1, "jet_pT", "Jet #it{p}_{T} spectrum;jet #it{p}_{T} (GeV);Counts", jet_pT]
    jet_pT_coarse: [1, "jet_pT_coarse", "Jet #it{p}_{T} spectrum (coarse binning);jet #it{p}_{T} (GeV);Counts", jet_pT_coarse]
    eec: [2, "eec", "EEC;jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]